### ISSUE TITLE
Change ordering from JLCPCB guide

### ISSUE THREAD

**Issue by AverseABFun** [hackclub/OnBoard#1059]
After following it, I noticed that after checking out it clears your cart and you now need to go to https://jlcpcb.com/user-center/orders to view the order. Also, various settings have been changed/removed and so it overall needs to be updated.

**Comment by blazecoding2009** [comment]
What are you trying to accomplish with this PR?

**Comment by AverseABFun** [comment]
> What are you trying to accomplish with this PR?

This is an issue

**Comment by LimesKey** [comment]
Are you talking about this doc [Ordering From JLCPCB](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md)? The link, https://jlcpcb.com/user-center/orders/, appears to be in that guide and works as expected. What various/settings need to be updated; everything looks the same or close enough for the guide?

You're free to make a PR and update the ordering from the JLCPCB documentation guide.

**Comment by AverseABFun** [comment]
Oh whoops, looks like I misread it. Closing this issue now
