### ISSUE TITLE
Create workshop content

### ISSUE THREAD

**Issue by maxwofford** [hackclub/OnBoard#145]
This is a meta-issue to track the following projects:

- https://github.com/hackclub/OnBoard/issues/144
- https://github.com/hackclub/OnBoard/issues/146
- https://github.com/hackclub/OnBoard/issues/147

**Comment by karamassie** [comment]
updated with others. closing and opening other tickets

**Comment by maxwofford** [comment]
@karamassie could you link those tickets here so we know what this was superseded by?
