### ISSUE TITLE
Mailing: makerspace envelopes

### ISSUE THREAD

**Issue by maxwofford** [hackclub/OnBoard#152]
These are packets of OnBoard posters with a letter signed by @zachlatta & quotes from our "Heroes of Tech" shipped to all makerspaces in the country in the hopes of bringing in technical teens at or around those spaces.

**Comment by karamassie** [comment]
MAILED today!

**Comment by zachlatta** [comment]
YAY! Go team!On Aug 18, 2023, at 16:42, kara ***@***.***> wrote:﻿
Closed #152 as completed.
