### ISSUE TITLE
Train new bank ops reviewer

### ISSUE THREAD

**Issue by maxwofford** [hackclub/OnBoard#155]
Setting up a review team for engineering has been a great way to reduce the bus factor of just having @kvnyng reviewing PRs. Let's get something like that setup for @daisybanks so she can take vacations again.

**Comment by karamassie** [comment]
can we close this @daisybanks  ?

**Comment by daisybanks** [comment]
Not yet @karamassie  - the person I want to train had to take on a bunch of other responsibilities with Bank growing so fast and this needed to wait so I didn't overwhelm them with things to look out for. Will hopefully train them up on OnBoard tomorrow during our sync though!

**Comment by maxwofford** [comment]
Marking as won't fix because @sarthaktexas has been doing the review (thank you) up until recently & now we're making the eng review and hcb review run under the same person!
