### ISSUE TITLE
Add 'how did you hear about onboard' question on form

### ISSUE THREAD

**Issue by karamassie** [hackclub/OnBoard#166]
To save time, maybe see sprig request form for what we used there. It's a drop down quick choice of how you heard about the project. (Club leader, hackathon, poster, friend etc)

**Comment by maxwofford** [comment]
I think this was a miscommunication in our last meeting-- I'll be the one taking this on

**Comment by karamassie** [comment]
here's sprig's https://airtable.com/appN9cSnDgORAM2bp/tblYLyzi8RySfkONg/viwMrglQ6x9pBSE0O?blocks=hide

**Comment by maxwofford** [comment]
As of this morning, there's now a dropdown with the option to fill out more details!

**Comment by maxwofford** [comment]
I should also clarify, we already have a required "how did you hear about us" field, but I've added the dropdown to make it quicker.
