### ISSUE TITLE
Slack channel broken

### ISSUE THREAD

**Issue by kcoderhtml** [hackclub/OnBoard#233]
When I tried to use the link for the #onboarding channel it gave me this error: 
![image](https://github.com/hackclub/OnBoard/assets/92754843/30131a7e-9376-44a3-a00b-5a05952beec0)
I have tried four times over the last 3 days.

**Comment by maxwofford** [comment]
@kcoderhtml thanks for flagging this! I'm looking into it now.

**Comment by maxwofford** [comment]
Hmmmm, I just went through the links in the README and they seem to have worked. @kcoderhtml, could you please send the URL linked for you? Where did you find the link?

**Comment by kcoderhtml** [comment]
I found the link on the README: https://hackclub.slack.com/archives/C056AMWSFKJ. It only seems to happen when I'm logged in to slack.

**Comment by maxwofford** [comment]
Oh, interesting! Could you try using this link to test if this works better? https://app.slack.com/client/T0266FRGM/C056AMWSFKJ

**Comment by kcoderhtml** [comment]
I think I found the problem. I hadn't completed the signup process in slack.
