### ISSUE TITLE
add woz quote above the fold

### ISSUE THREAD

**Issue by karamassie** [hackclub/OnBoard#336]
as per zach. this helps legitimize the validity of the grant esp for those skeptical of free things

**Comment by karamassie** [comment]
@sarthaktexas can you literally move it over the title ? it's still not showing up on mobile.

**Comment by maxwofford** [comment]
Closed this here https://github.com/hackclub/site/pull/1080#issuecomment-1954726432

**Comment by maxwofford** [comment]
This adds a banner above the fold for both mobile and desktop. Still to fix:

- Move old woz quote (which is slightly longer) further down on the page or remove entirely
- Awkward spacing on desktop view
