### ISSUE TITLE
Unable to join Slack

### ISSUE THREAD

**Issue by aaronjamt** [hackclub/OnBoard#355]
The Slack workspace won't let me use my email address (since I don't have an `@hack.af` or `@hackclub.com` email). Is there any chance I can get an invitation sent to my email? It says to "Contact the workspace administrator at Hack Club for an invitation" but I don't know of a better way to get in touch than to open an issue here. Apologies if this is the wrong place for this!

![image](https://github.com/hackclub/OnBoard/assets/13600347/827674fc-2546-4da9-a200-ead1497a3e47)

**Comment by maxwofford** [comment]
@aaronjamt use the link in the pr template for access: https://hackclub.com/slack!

**Comment by aaronjamt** [comment]
> @aaronjamt use the link in the pr template for access: https://hackclub.com/slack!

Ah, thanks! I must have missed that link, I apologize!
