### ISSUE TITLE
Tagging wrong daisy on greeter bot

### ISSUE THREAD

**Issue by maxwofford** [hackclub/OnBoard#56]
<img width="931" alt="Screenshot 2023-05-29 at 20 44 29" src="https://github.com/hackclub/OnBoard/assets/5891442/9ec994ad-88c1-4756-ab33-6d78e0a2a21e">

We've tagged the wrong Daisy!

**Comment by bykevinyang** [comment]
Yeah that was fixed by @garyhtou in [PR 54](https://github.com/hackclub/OnBoard/pull/54)
