### ISSUE TITLE
Only trigger CI greeter when user is submitting a PR for the grant

### ISSUE THREAD

**Issue by maxwofford** [hackclub/OnBoard#61]
My PRs to make improvements get automatically tagged "submission", and I get a message about verifying my high school enrollment. Could we only trigger the greeter on PRs with a specific message in their description to prevent this?

**Comment by maxwofford** [comment]
Update, I think we can filter by skipping any PR that's already been labeled with the "dev" label

**Comment by GalaxyGamingBoy** [comment]
@maxwofford May I take this one?

**Comment by maxwofford** [comment]
Meh, for now this is just a manual process but I think that's fine!
