### ISSUE TITLE
Can not use the grant

### ISSUE THREAD

**Issue by ArthusPVP** [hackclub/OnBoard#702]
Hello,
I can not use the grant. 
thx
![image](https://github.com/hackclub/OnBoard/assets/117471715/55e00b4a-46d9-47c0-bbf5-f2fa561b38fa)
Arthus

**Comment by MichaByte** [comment]
Hello @ArthusPVP!

The grant can only be used at our approved vendors. Please see [VENDORS.md](https://github.com/hackclub/OnBoard/blob/main/docs/VENDORS.md) to find one that works for you. PCBWay is not allowed since they carry items other than PCBs.
