### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by maxwofford** [hackclub/OnBoard#73]
<img width="1393" alt="Screenshot 2023-06-01 at 11 51 09" src="https://github.com/hackclub/OnBoard/assets/5891442/16396e76-c6f1-47e4-b3cc-a83dfc931084">

This error popped up on this GH action job https://github.com/hackclub/OnBoard/actions/runs/5143884593/jobs/9259461095?pr=70

**Comment by kvnyng** [comment]
I just deleted those workflows and will be pivoting towards a Github Application.
